### PR TITLE
6 mtc4bt large controller configjson files crash the controller at start up

### PR DESCRIPTION
**Pull request by raymondbrink**
Moved away from StaticJsonDocument (on the stack) to DynamicJsonDocument (on the heap).

You can now put each loco config into a separate file (max. 4k):

image

You can even combine loco config files with inline loco configurations (for backwards compatibility):

image

### CODE REVIEW

**Comment by Mattzobricks** [comment]
Tested, works fine.

**Comment by Mattzobricks** [comment]
Let's merge it into develop, not master.

**Comment by raymondbrink** [comment]
I rebased this feature into develop, so it now includes the latest changes for PU hub onboard LED control.

**Comment by Mattzobricks** [comment]
Very nice, thank you.

**Pull request merged**
