### PR TITLE
Feature memory debug

### PR DESCRIPTION
**Pull request by Hilbert70**
- Added a DUMMY driver to test
- fixed the memory leak.
- Removed taskloops 
- removed internal message queue
- made parent hub code more inherent friendly (private->protected)
- tweaked nimble (no more server components)
- moved to nimble 1.4.0

### CODE REVIEW

**Comment by Mattzobricks** [comment]
From what I see, Hilbert has introduced a DUMMY hub in addition to the LEGO PU Hub and SBrick. The question is, if we need and want that additional complexity in the master branch.

**Comment by Hilbert70** [comment]
The dummy hub can be removed, it is two files and some changes in the code. Those code changes can me made into comments to make it easier to add future hubs. 
And it is no additional complexity, the dummy code was needed to exclude Nimble call "pollution".

**Comment by Mattzobricks** [comment]
This branch was created on Nov 24th from commit 095a5f3fd37615e97e608734e9aba43d99711d70. Since then, we had two releases. Will this be a problem when we merge it?

**Comment by Hilbert70** [comment]
Github does not give any merge conflicts, so it should be good.

**Comment by Mattzobricks** [comment]
The question is rather, what new features and bugfixes you are going to undo when we merge it.

**Comment by Hilbert70** [comment]
None, otherwise we would have a merge conflict, have faith in git ;-)

**Comment by Mattzobricks** [comment]
After some more testing, I have isolated the memory leak fix, and just applied this change. This works fine. I merged the memory leak fix into the develop branch.

**Pull request closed without merging**
