### PR TITLE
79 make wired internet possible using a w5500 module

### PR DESCRIPTION
**Pull request by Hilbert70**
Tested:
 - with -DWIRED flag, and it is working with or without a network cable connected
 - without -DWIRED, also working (The include Ethernet module is included, but non functional)
 - status led is working
 - OTA is over the AIR not CABLE, the ArduinoOTA code is hard wired to WiFi.h
 - only on startup the wired connection is setup, if not found it will fallback to wifi, after startup, it will **NOT** fallback to Wifi. If the wire is disconnected it will reconnect after reinserting the wire, the status led will show this :-D

Documentation:
 - add how to wire and configure in the module Readme.md

### CODE REVIEW

**Comment by Mattzobricks** [comment]
@Hilbert70, github says that the branch has conflicts that must be resolved...

**Comment by Mattzobricks** [comment]
Suggestions:
- enhance MTC4BT documentation on the website
- add a line in the my_platform.ini.example file saying:
; To use w5500 module for wired connections, uncomment the line -DWIRED

What do you think?

**Comment by Hilbert70** [comment]
- Website documentation can not be part of this pull request, copy it out of the readme.
- Comment will be added.
- somehow git can't handle the conflict in the readme.md, will be resolved during merge

**Review by Mattzobricks — APPROVED** [review]
Thank you, Hilbert.

**Pull request merged**
